# Python Review

In [2]:
import numpy as np

## Variables

We can think of a variable as a name we assign to a particular object in Python. For example:

In [16]:
# Assign a small array to variable a
a = np.array([[1,1,2],[3,5,8]])

When we run the cell, we store the variables and their value. We can view a variable’s value in two ways from within our Jupyter notebook:

1. running a cell with the variable name

2. using the `print` function to print the value

In [4]:
# Show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Print the value 
print(a)

[[1 1 2]
 [3 5 8]]


## Convention: Use `snake_case` for naming variables

This is the convention we will use in the course. Why? `my_variable` or `MyVariable` or `myVariable`.
PEP 8 - Style Guide for python code recommends snake_case.

**remember that variable names should be both descriptive and concise**

## Objects

**object:** (informally speaking) is a bundle of *properties* and *actions* about something specific

Example:

object: data frame
properties: number of rows, names of columns, and date created
actions: selecting a specific row or adding a new column

A variable is the name we give a spec obj and the same obj can be referenced by diff variables

## Types

Every object in Python has a **type**, the type tells us what kind of object we have.
We can also call the type of an object, the **class** of the object

In [14]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

the **numpy.ndarray** is the core object/data type of the numpy package

In [15]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

`numpy.int64` is not the standard integer tyoe `int`

`numpy.int64` is a special data type in Numpy telling us that 1 is an integer stored as a 64-bit number

Check-in: access the value 5 in array `a`

In [17]:
a[1,1]

5

## Functions 

`print` was our first example of a Python **function**

Functions take in a set of **arguments**, sep by commas, and use those arguments to create an **output**.

In the course, we'll be using argument and parameter interchangeably. but they do have slightly diff meanings.

We can ask for info about what a function does by executing `?` followed by function name.

In [20]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we obtain is a **docstring**, a special type of commment that is used to document how a function (or a class, or module) works.

Notice that there are diffferent types of arguments inside the function's parentheses.

roughly speaking, a function has 2 types of arguments:

- **non-optional arguments**: arguments  *you* have to specify for the function to work

- **optional arguments**: arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis () in the form `optional_argument = default_value.`

Example

`end` is a parameter in `print` with default value a new new line
We can pass the value `:)` to this parameter so that it finished the line with `:)` instead

In [22]:
print('change the end parameter', end = ':)')

change the end parameter:)

## Attributes and methods

An object in python has attributes and methods

- **attributes**: a property of the object, some piece of information about it
- **method**: a procedure associated

Example: 

Numpy arrays have many methods and attributes. For example:

In [24]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [26]:
# T is an example of an attribute, it returns the transpose of array
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [28]:
type(a.T)

numpy.ndarray

In [30]:
# shape - another attribute tells us the shape of the array
print(a.shape)
print(type(a.shape))

(2, 3)
<class 'tuple'>


In [35]:
# ndim is an attribute holding the number of array dimensions
print('dim:', a.ndim, '| type:', type(a.ndim))

dim: 2 | type: <class 'int'>


Attributes can have many different data types. 

Some examples of methods.

In [37]:
# the min method returns the minimum value in the array along a specified axis
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

Remeber, methods are **functions** associated with an object. We can confirm this!

In [39]:
# method tolist() transforms array into list
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [41]:
type(a.tolist())

list

In [43]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


## Exercise

1. read the `print` function help. what is the type of argument `sep`? is this an optional/default or non-optional/non-default argument? why?

2. Create two new variables, one with the integer value 77 and one with string 99

3. print 77%99%77

`sep` is a default argument because it appears inside the ()

In [45]:
b = 77
c = '99'

In [46]:
type(b)

int

In [48]:
type(c)

str

In [49]:
print(b,c,b, sep = '%')

77%99%77
